.import QtQuick as QQ
.import "./theme-utils.mjs" as ThemeUtils


const specColors = {
	black: '#000000',
	white: '#FFFFFF',
	red10: '#FA7E75',
	red20: '#FA665C',
	red30: '#F94F44',
	red40: '#F8382B',
	red50: '#E81608',
	red60: '#CF1407',
	red70: '#B71106',
	red80: '#9E0F05',
	red90: '#850D04',
	green10: '#5ED007',
	green20: '#54BB06',
	green30: '#4BA605',
	green40: '#419104',
	green50: '#387C04',
	green60: '#2F6803',
	green70: '#255302',
	green80: '#1C3E02',
	green90: '#122901',
	blue10: '#75AFFA',
	blue20: '#5CA1FA',
	blue30: '#4492F9',
	blue40: '#2B84F8',
	blue50: '#1276F7',
	blue60: '#0869E8',
	blue70: '#075ECF',
	blue80: '#0653B7',
	blue90: '#05489E',
	cyan10: '#bdeffa',
	cyan20: '#98e6f7',
	cyan30: '#74dcf5',
	cyan40: '#4fd3f2',
	cyan50: '#2bcaef',
	cyan60: '#11bbe2',
	cyan70: '#0e9ebd',
	cyan80: '#0b7e99',
	cyan90: '#0a6f87',
	magenta10: '#efbdfa',
	magenta20: '#e698f7',
	magenta30: '#dc74f5',
	magenta40: '#d34ff2',
	magenta50: '#ca2bef',
	magenta60: '#bb11e2',
	magenta70: '#9e0ebd',
	magenta80: '#7e0b99',
	magenta90: '#6f0a87',
	yellow10: '#faefbd',
	yellow20: '#f7e698',
	yellow30: '#f5dc74',
	yellow40: '#f2d34f',
	yellow50: '#efca2b',
	yellow60: '#e2bb11',
	yellow70: '#bd9e0e',
	yellow80: '#997e0b',
	yellow90: '#876f0a',
	grey10: '#cfcfd7',
	grey20: '#b9b9c5',
	grey30: '#a4a4b3',
	grey40: '#8e8ea1',
	grey50: '#787890',
	grey60: '#65657b',
	grey70: '#545465',
	grey80: '#4b4b5b',
	grey90: '#424250',
};

const sizes = {
	font: {
		xxsm: 12,
		xsm: 16,
		sm: 20,
		md: 24,
		lg: 28,
		xlg: 32,
		xxlg: 36,
		auto: 24,
	},
	button: {
		xxsm: 30,
		xsm: 36,
		sm: 42,
		md: 48,
		lg: 54,
		xlg: 60,
		xxlg: 66,
		auto: null,
	},
	icon: {
		xxsm: 28,
		xsm: 32,
		sm: 36,
		md: 40,
		lg: 44,
		xlg: 48,
		xxlg: 52,
		auto: null,
	},
	glyph: {
		xxsm: 12,
		xsm: 14,
		sm: 16,
		md: 24,
		lg: 32,
		xlg: 38,
		xxlg: 44,
		auto: null,
	},
	item: {
		xxsm: 36,
		xsm: 42,
		sm: 48,
		md: 54,
		lg: 60,
		xlg: 66,
		xxlg: 72,
		auto: null,
	},
	divider: {
		xxsm: 0.5,
		xsm: 0.75,
		sm: 1,
		md: 2,
		lg: 3,
		xlg: 4,
		xxlg: 5,
		auto: null,
	},
};

const fonts = {
	regular: null,
	semi: null,
	bold: null,
	mono: null,
};

const defaultColorSet = {
	text: 'text.primary',
	textHover: 'text.primary',
	textActive: 'text.primary',
	bg: 'bg.primary',
	bgHover: 'bg.primary',
	bgActive: 'bg.primary',
	border: 'transparent',
	borderHover: 'transparent',
	borderActive: 'transparent',
};

const defaultColorSetGhost = {
	text: 'text.primary',
	textHover: 'text.primary',
	textActive: 'text.primary',
	bg: 'bg.primary',
	bgHover: 'bg.primary',
	bgActive: 'bg.primary',
	border: 'text.primary',
	borderHover: 'text.primary',
	borderActive: 'text.primary',
};

const defaultColorSetText = {
	text: 'text.primary',
	textHover: 'text.primary',
	textActive: 'text.primary',
	bg: 'transparent',
	bgHover: 'transparent',
	bgActive: 'transparent',
	border: 'transparent',
	borderHover: 'transparent',
	borderActive: 'transparent',
};

const colorSets = {
	none: {
		text: 'transparent',
		textHover: 'transparent',
		textActive: 'transparent',
		bg: 'transparent',
		bgHover: 'transparent',
		bgActive: 'transparent',
		border: 'transparent',
		borderHover: 'transparent',
		borderActive: 'transparent',
	},
	primary: defaultColorSet,
	primaryghost: defaultColorSetGhost,
	primarytext: defaultColorSetText,
	secondary: defaultColorSet,
	secondaryghost: defaultColorSetGhost,
	secondarytext: defaultColorSetText,
	tertiary: defaultColorSet,
	tertiaryghost: defaultColorSetGhost,
	tertiarytext: defaultColorSetText,
	accent: defaultColorSet,
	accentghost: defaultColorSetGhost,
	accenttext: defaultColorSetText,
	success: defaultColorSet,
	successghost: defaultColorSetGhost,
	successtext: defaultColorSetText,
	warning: defaultColorSet,
	warningghost: defaultColorSetGhost,
	warningtext: defaultColorSetText,
	error: defaultColorSet,
	errorghost: defaultColorSetGhost,
	errortext: defaultColorSetText,
	light: defaultColorSet,
	lightghost: defaultColorSetGhost,
	lighttext: defaultColorSetText,
	grey: defaultColorSet,
	greyghost: defaultColorSetGhost,
	greytext: defaultColorSetText,
	dark: defaultColorSet,
	darkghost: defaultColorSetGhost,
	darktext: defaultColorSetText,
};

const defaultTheme = {
	name: "Default",
	colors: {
		spec: specColors,
		text: {
			primary: specColors.black,
			primaryplus: specColors.black,
			primaryminus: specColors.black,
			primaryalt: specColors.black,
			primaryaltplus: specColors.black,
			primaryaltminus: specColors.black,
			secondary: specColors.black,
			secondaryplus: specColors.black,
			secondaryminus: specColors.black,
			tertiary: specColors.black,
			tertiaryplus: specColors.black,
			tertiaryminus: specColors.black,
			accent: specColors.black,
			accentplus: specColors.black,
			accentminus: specColors.black,
			success: specColors.black,
			successplus: specColors.black,
			successminus: specColors.black,
			warning: specColors.black,
			warningplus: specColors.black,
			warningminus: specColors.black,
			error: specColors.black,
			errorplus: specColors.black,
			errorminus: specColors.black,
			contrast: specColors.black,
		},
		bg: {
			primary: specColors.white,
			primaryplus: specColors.white,
			primaryminus: specColors.white,
			primaryalt: specColors.white,
			primaryaltplus: specColors.white,
			primaryaltminus: specColors.white,
			secondary: specColors.white,
			secondaryplus: specColors.white,
			secondaryminus: specColors.white,
			tertiary: specColors.white,
			tertiaryplus: specColors.white,
			tertiaryminus: specColors.white,
			accent: specColors.white,
			accentplus: specColors.white,
			accentminus: specColors.white,
			success: specColors.white,
			successplus: specColors.white,
			successminus: specColors.white,
			warning: specColors.white,
			warningplus: specColors.white,
			warningminus: specColors.white,
			error: specColors.white,
			errorplus: specColors.white,
			errorminus: specColors.white,
			contrast: specColors.white,
		},
	},
	fonts,
	sizes,
	shadows: {
		none: null,
		sm: { size: 1, color: '#33000000' },
		md: { size: 2, color: '#66000000' },
		lg: { size: 3, color: '#99000000' },
	},
	shadowsText: {
		none: null,
		sm: { style: QQ.Text.Outline, styleColor: '#55000000' },
		md: { style: QQ.Text.Outline, styleColor: '#88000000' },
	},
	shapes: ThemeUtils.mapShapes(4, 8, 12, 16),
	borders: { sm: 1, md: 2, lg: 3, xlg: 4 },
	colorSets,
};
